
- name: Install MySQL
  apt:
    pkg:
      - mariadb-server
      - mariadb-common
      - mariadb-client
    state: present

- name: Install MySQL PHP Lib
  apt:
    pkg:
      - php5-mysql
    state: present
  when: php_version == 5

- name: Install MySQL PHP Lib
  apt:
    pkg:
      - php-mysql
    state: present
  when: php_version == 7

