- name: Install base packages
  apt:
    pkg:
        - less
        - nano
        - curl
        - wget
        - rsync
        - htop
        - tree
        - bash-completion
        - haveged
        - fail2ban
        - git
        - diffutils
        - patch
    state: present
