- block:
    - name: APT | Install DotDeb key
      apt_key: 
        url: "https://www.dotdeb.org/dotdeb.gpg"
        state: present

    - name: APT | Add Dotdeb repository
      apt_repository:
        repo: "deb http://packages.dotdeb.org jessie all"
        filename: dotdeb
        state: present

  when: ansible_distribution_release == "jessie"

- name: Install PHP 7
  apt:
    pkg:
        - php
        - php-cgi
        - php-cli
        - php-common
        - php-curl
        - php-fpm
        - php-gd
        - php-geoip
        - php-gmp
        - php-intl
        - php-json
        - php-mbstring
        - php-memcached
        - php-mysql
        - php-opcache
        - php-pear
        - php-readline
        - php-sqlite3
        - php-tidy
        - php-xml
        - php-zip
    state: present
